# azure-pipeline.yml

trigger:
  branches:
    include:
      - main  # Update with your main branch name

pool:
    vmImage: 'windows-latest'

steps:

- task: FlutterInstall@0
  inputs:
    mode: 'auto'
    channel: 'stable'
    version: 'latest'    

- script: flutter clean
  displayName: 'Flutter clean'

- script: flutter pub get
  displayName: 'Flutter pub get'

- script: flutter build apk --release
  displayName: 'Flutter build APK release'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/build/app/outputs/flutter-apk/app-release.apk'
    ArtifactName: 'apk'

# - script: flutter analyze
#   displayName: 'Flutter analyze'

# - script: flutter test --coverage
#   displayName: 'Flutter tests with coverage'

# - task: PublishCodeCoverageResults@1
#   inputs:
#     codeCoverageTool: 'Cobertura'
#     summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/lcov.info'
#     failIfCoverageEmpty: false

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(System.DefaultWorkingDirectory)/build/ios/iphoneos'
#     ArtifactName: 'ios'

# Add additional steps for Android builds, distribution, etc. as needed